//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HolaAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepartPlan
    {
        public string depart_list { get; set; }
        public int hotel_fk { get; set; }
        public Nullable<System.DateTime> date_dep_start { get; set; }
        public Nullable<System.TimeSpan> time { get; set; }
        public int PAX { get; set; }
    }
}
