//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HolaAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int ID { get; set; }
        public int sale_fk { get; set; }
        public decimal sum { get; set; }
        public System.DateTime date_payment { get; set; }
        public System.DateTime date_update { get; set; }
        public int paid_to { get; set; }
        public string method { get; set; }
        public string C_type { get; set; }
    
        public virtual Sale Sale { get; set; }
    }
}
