//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HolaAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoldActivity
    {
        public int ID { get; set; }
        public string PNR { get; set; }
        public int agency_fk { get; set; }
        public int sale_fk { get; set; }
        public int activity_fk { get; set; }
        public Nullable<int> event_fk { get; set; }
        public System.DateTime date_update { get; set; }
        public bool canceled { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual Agency Agency { get; set; }
        public virtual Sale Sale { get; set; }
    }
}
