//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HolaAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Upload_temp
    {
        public string PNR { get; set; }
        public string names { get; set; }
        public int PAX { get; set; }
        public string num_arr { get; set; }
        public System.DateTime date_arr { get; set; }
        public string num_dep { get; set; }
        public System.DateTime date_dep { get; set; }
        public string phone { get; set; }
        public string hotel_name { get; set; }
        public string comments { get; set; }
        public int ID { get; set; }
    }
}
